### ISSUE TITLE
Game Pieces

### ISSUE THREAD

**Issue by amaraldatwit** [amaraldatwit/BlockCycles#2]
2.1.2.	Game Pieces
    2.1.2.1.	 [REQ 8] The system shall allow a game piece to be composed of geometric sections.
    2.1.2.2.	 [REQ 9] The system shall allow a game piece to be placed into the game board.
    2.1.2.3.	 [REQ 10] The system shall allow game pieces to be rotated 90° on spacebar press.
    2.1.2.4.	 [REQ 11] The system shall allow game pieces to be moved until level completion.

**Comment by DJWickWack** [comment]
Game piece design has been completed
